[package]
name = "funder"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.2.1", features = ["borsh-derive", "derive"] }
solana-program = "1.17.7"

[lib]
crate-type = ["cdylib", "lib"]
