import "../styles/globals.css";
import type { Metadata } from "next";
import WalletContextProvider from "../components/WalletContextProvider";

export const metadata: Metadata = {
  title: "Funder",
  description: "Generated by Xavier Griffith",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WalletContextProvider>
          <div>{children}</div>
        </WalletContextProvider>
      </body>
    </html>
  );
}
