import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import WalletContextProvider from "../components/WalletContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Funder",
  description: "Generated by Xavier Griffith",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletContextProvider>
          <div>{children}</div>
        </WalletContextProvider>
      </body>
    </html>
  );
}
